### PR TITLE
Scratch API

### PR DESCRIPTION
**Pull request by CosmicWebServices**
Made to interact with https://scratch.mit.edu/projects/116422317/

DO NOT MERGE!

### CODE REVIEW

**Comment by CosmicWebServices** [comment]
DO NOT MERGE!

**Comment by CosmicWebServices** [comment]
@joker314 Can u check this out?

**Comment by ghost** [comment]
hi

**Comment by ghost** [comment]
Hmmm...  I prefer it the way it is.  Don't really need to complicate it for the user. :)

**Comment by ghost** [comment]
@CosmicWebServices c'mon

**Comment by CosmicWebServices** [comment]
ok I will just leave this ope till @joker314 sees it

**Comment by ghost** [comment]
@joker314 is going to be away for a week from what I know.

**Comment by CosmicWebServices** [comment]
Oh OK

**Comment by joker314** [comment]
I was away for a week a while ago?

Anyway, do we need the Scratch API, or can we get away without it?

**Comment by CosmicWebServices** [comment]
We could get away without it I will make this a future release

**Comment by CosmicWebServices** [comment]
I will close this for now

**Pull request closed without merging**
