### PR TITLE
G0577 Branch

### PR DESCRIPTION
**Pull request by tacofart08**
Small edits of code to continuously check for changes, but may need delay?
- [x] Make pull request
- [ ] Merged
- [ ] Code Works?

Sending to:
@CosmicWebServices 
@bwbw223 
@joker314 
Not sure if I forgot anyone.

### CODE REVIEW

**Comment by CosmicWebServices** [comment]
What does this do?

**Comment by ghost** [comment]
We don't need it in a forever loop because we are using event listeners...
and use `while (true) {...}` instead of `while (1==1) {...}`

**Comment by ghost** [comment]
@CosmicWebServices I don't think we'll add him (from what I've seen)
I can do the same!

**Comment by CosmicWebServices** [comment]
OK should we close this?
Whoah @bwbw223 can edit my comments!!!

**Comment by CosmicWebServices** [comment]
@bwbw223

**Comment by ghost** [comment]
Idk, maybe we should wait and see If he actually adds a feature.

**Comment by CosmicWebServices** [comment]
K

**Comment by CosmicWebServices** [comment]
I will close this for the moment

**Pull request closed without merging**
