### PR TITLE
Update users.json

### PR DESCRIPTION
**Pull request by joker314**
Don't merge yet!

### CODE REVIEW

**Comment by ghost** [comment]
Why do we need this?

**Comment by joker314** [comment]
See my other thing, I don't believe that is how require works: http://openmymind.net/2012/2/3/Node-Require-and-Exports/

**Comment by ghost** [comment]
It does: http://www.bennadel.com/blog/2908-you-can-use-require-to-load-json-javascript-object-notation-files-in-node-js.htm

**Comment by ghost** [comment]
https://nodejs.org/dist/latest-v6.x/docs/api/modules.html#modules_file_modules

**Comment by ghost** [comment]
It looks for .json

**Comment by joker314** [comment]
Fine, I know why the error

**Comment by ghost** [comment]
Yeah the error is gone.  There were too many failed login attempts and it wanted a captcha

**Pull request closed without merging**
